# Generated by Django 5.2.12 on 2026-03-31 18:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLinkType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'organization link type',
                'verbose_name_plural': 'organization link types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=120)),
                ('last_name', models.CharField(db_index=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('special_events', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('archive_person', 'Can archive/unarchive people (soft delete)')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='relations.organization', verbose_name='parent organization')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'permissions': [('archive_organization', 'Can archive/unarchive organizations (soft delete)')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('visiting', 'Visiting'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('zipcode', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['address_type', 'label', 'city'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='relations_a_content_0def55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('comm_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('fax', 'Fax')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'communication',
                'verbose_name_plural': 'communications',
                'ordering': ['comm_type', '-is_primary', 'label', 'value'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='relations_c_content_e02b33_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='relations.organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='relations.organization')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relations.organizationlinktype')),
            ],
            options={
                'verbose_name': 'organization link',
                'verbose_name_plural': 'organization links',
                'ordering': ['from_organization', 'link_type', 'to_organization'],
                'constraints': [models.UniqueConstraint(fields=('from_organization', 'to_organization', 'link_type'), name='relations_unique_org_link_triple')],
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations', to='relations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='relations.person')),
            ],
            options={
                'verbose_name': 'affiliation',
                'verbose_name_plural': 'affiliations',
                'ordering': ['-start_date', '-end_date'],
                'indexes': [models.Index(fields=['person', 'end_date'], name='relations_a_person__7b4472_idx'), models.Index(fields=['organization', 'end_date'], name='relations_a_organiz_77aef2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('platform', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'social profile',
                'verbose_name_plural': 'social profiles',
                'ordering': ['platform', 'handle'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='relations_s_content_5e5f91_idx')],
            },
        ),
    ]
