# Generated by Django 5.2.12 on 2026-03-31 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategoryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'organization category',
                'verbose_name_plural': 'organization categories',
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='categories',
        ),
        migrations.AddField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='relations.organizationcategorytag', verbose_name='categories'),
        ),
    ]
