# Generated by Django 5.2.12 on 2026-03-31 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_organizationcategorytag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='special_events',
        ),
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='primary'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_province',
            field=models.CharField(blank=True, max_length=120, verbose_name='state / province'),
        ),
        migrations.AddField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='street address 2'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='primary role'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=200, verbose_name='industry / sector'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Primary relationship category (customer/supplier/partner/strategic/internal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_primary', to='relations.organizationcategorytag', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='registration / chamber of commerce number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id_vat',
            field=models.CharField(blank=True, max_length=80, verbose_name='tax ID / VAT number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, verbose_name='background / bio'),
        ),
        migrations.AddField(
            model_name='person',
            name='pronouns',
            field=models.CharField(blank=True, max_length=60, verbose_name='gender / pronouns'),
        ),
        migrations.AddField(
            model_name='person',
            name='title_prefix',
            field=models.CharField(blank=True, max_length=40, verbose_name='title / prefix'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('visiting', 'Visiting'), ('home', 'Home'), ('postal', 'Postal'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='street address 1'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='event name / type')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='event date')),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_events', to='relations.person')),
            ],
            options={
                'verbose_name': 'special event',
                'verbose_name_plural': 'special events',
                'ordering': ['event_date', 'name'],
            },
        ),
    ]
