# Generated by Django 5.2.12 on 2026-04-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_remove_person_special_events_address_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Primary relationship category (customer, prospect, supplier, partner, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_primary', to='relations.organizationcategorytag', verbose_name='category'),
        ),
    ]
