# Generated by Django 5.2.12 on 2026-04-02 21:29

from django.db import migrations, models


def backfill_organization_unit_kind(apps, schema_editor):
    Organization = apps.get_model('relations', 'Organization')
    Organization.objects.filter(parent_id__isnull=False).update(unit_kind='department')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_organizationcategorytag_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='unit_kind',
            field=models.CharField(choices=[('legal_entity', 'Legal entity / company'), ('department', 'Department'), ('branch', 'Branch / site / office'), ('team', 'Team'), ('other', 'Other')], db_index=True, default='legal_entity', help_text='What this row represents (company vs department, branch, etc.).', max_length=32),
        ),
        migrations.RunPython(backfill_organization_unit_kind, noop_reverse),
    ]
