# Generated by Django 5.2.12 on 2026-04-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('relations', '0006_organization_unit_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='employer_organization',
            field=models.ForeignKey(blank=True, help_text='For a person: which company this email/phone is for. Leave empty for personal or shared contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_communications_at_employer', to='relations.organization', verbose_name='linked employer'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['employer_organization'], name='relations_c_employe_0bbea9_idx'),
        ),
    ]
