# Generated by Django 5.2.12 on 2026-04-05 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_productimage_options_productimage_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('method', models.CharField(choices=[('cost_markup', 'Cost + markup %'), ('gross_margin', 'Gross margin %'), ('msrp_discount', 'MSRP − discount %'), ('list_discount', 'List price − discount %'), ('fixed_multiplier', 'Fixed multiplier (cost × factor)')], max_length=30, verbose_name='pricing method')),
                ('value', models.DecimalField(decimal_places=6, help_text='Markup %, gross margin %, or discount % (0–100). For "Fixed multiplier" enter the factor directly (e.g. 1.35 for 35% above cost).', max_digits=12, verbose_name='method value')),
                ('rounding', models.CharField(choices=[('none', 'None (exact)'), ('nearest_cent', 'Nearest cent (0.01)'), ('nearest_10c', 'Nearest 10 cents (0.10)'), ('nearest_50c', 'Nearest 50 cents (0.50)'), ('nearest_euro', 'Nearest whole unit (1.00)'), ('nearest_5', 'Nearest 5'), ('nearest_10', 'Nearest 10'), ('custom', 'Custom increment')], default='nearest_cent', max_length=20, verbose_name='rounding')),
                ('rounding_increment', models.DecimalField(blank=True, decimal_places=6, help_text='Required when rounding is "Custom increment" (e.g. 0.05 or 2.50).', max_digits=12, null=True, verbose_name='custom rounding increment')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
            ],
            options={
                'verbose_name': 'pricing rule',
                'verbose_name_plural': 'pricing rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRuleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('include_subcategories', models.BooleanField(default=True, help_text='Also apply this rule to all descendant categories.', verbose_name='include subcategories')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower number = higher priority when multiple rules could apply.', verbose_name='priority')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_assignments', to='catalog.productcategory', verbose_name='category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_assignments', to='catalog.product', verbose_name='product')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pricing.pricingrule', verbose_name='pricing rule')),
            ],
            options={
                'verbose_name': 'pricing rule assignment',
                'verbose_name_plural': 'pricing rule assignments',
                'ordering': ['priority', 'rule__name'],
            },
        ),
    ]
