# Generated by Django 5.2.12 on 2026-04-05 08:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_asset_organization_transfer'),
        ('relations', '0007_communication_employer_organization'),
        ('sales', '0005_shipping_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('formula', models.TextField(help_text='Python-style arithmetic expression. Allowed operators: + − * / ( ). Use variable names defined below plus built-ins: duration_years, duration_months, quote_total, order_total, asset_purchase_price.')),
                ('result_label', models.CharField(default='Annual cost', help_text='Label shown next to the computed result (e.g. "Annual cost" or "Total contract value").', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'contract template',
                'verbose_name_plural': 'contract templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text='Short identifier (e.g. mechanic, engineer). Used as the variable name in formulas.', unique=True)),
                ('description', models.TextField(blank=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'service rate',
                'verbose_name_plural': 'service rates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('computed_result', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='assets.asset', verbose_name='linked asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='relations.organization', verbose_name='customer organization')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sales.quote', verbose_name='linked quote')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sales.salesorder', verbose_name='linked sales order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contracttemplate')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplateVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Python identifier used in the formula (e.g. mechanic_hours, setup_fee).', max_length=80)),
                ('label', models.CharField(help_text='Human-readable label shown in the UI.', max_length=200)),
                ('variable_type', models.CharField(choices=[('user_input', 'User input'), ('service_rate', 'Service rate'), ('constant', 'Constant')], max_length=20)),
                ('constant_value', models.DecimalField(blank=True, decimal_places=6, help_text='Fixed value. Required when type is "Constant".', max_digits=18, null=True)),
                ('default_value', models.DecimalField(blank=True, decimal_places=6, help_text='Default value pre-filled for user input fields.', max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, help_text='Display unit (e.g. hours, %, EUR).', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='contracts.contracttemplate')),
                ('service_rate', models.ForeignKey(blank=True, help_text='Required when type is "Service rate".', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_variables', to='contracts.servicerate')),
            ],
            options={
                'verbose_name': 'template variable',
                'verbose_name_plural': 'template variables',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractVariableValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_values', to='contracts.contract')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_values', to='contracts.contracttemplatevariable')),
            ],
            options={
                'verbose_name': 'variable value',
                'verbose_name_plural': 'variable values',
                'ordering': ['variable__sort_order', 'variable__name'],
                'unique_together': {('contract', 'variable')},
            },
        ),
    ]
