# Generated by Django 5.2.12 on 2026-04-04 10:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_productimage_options_productimage_file_size_and_more'),
        ('relations', '0006_organization_unit_kind'),
        ('sales', '0005_shipping_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional display name; UI falls back to product name.', max_length=255)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('asset_tag', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='internal asset tag')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('expected_end_of_life_date', models.DateField(blank=True, help_text='Planned replacement horizon for MJOP and sales advice.', null=True, verbose_name='expected end of life')),
                ('status', models.CharField(choices=[('pending_install', 'Pending installation'), ('in_service', 'In service'), ('under_repair', 'Under repair'), ('warranty', 'In warranty'), ('eol_near', 'End of life — plan replacement'), ('retired', 'Retired'), ('disposed', 'Disposed')], db_index=True, default='in_service', max_length=24)),
                ('location_note', models.CharField(blank=True, help_text='Site, room, rack, etc.', max_length=255, verbose_name='location')),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.ForeignKey(blank=True, help_text='Optional link to the sales order line that sourced this unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='sales.orderline', verbose_name='order line')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_assets', to='relations.organization', verbose_name='customer organization')),
                ('person', models.ForeignKey(blank=True, help_text='Optional person at the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_owned', to='relations.person', verbose_name='contact / owner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assets', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReplacementRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rationale', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('superseded', 'Superseded')], db_index=True, default='open', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_recommendations', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_recommendations_created', to=settings.AUTH_USER_MODEL)),
                ('suggested_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_recommendations_from', to='catalog.product')),
            ],
            options={
                'verbose_name': 'replacement recommendation',
                'verbose_name_plural': 'replacement recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='relations.organization', verbose_name='customer organization')),
            ],
            options={
                'verbose_name': 'maintenance plan (MJOP)',
                'verbose_name_plural': 'maintenance plans (MJOP)',
                'ordering': ['-valid_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlanLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_year', models.PositiveIntegerField(db_index=True, help_text='Calendar year this line applies to (e.g. 2027).')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_promoted', models.BooleanField(db_index=True, default=False, help_text='Highlight in customer-facing MJOP summaries and sales follow-up.', verbose_name='promote to customer')),
                ('estimated_cost_note', models.CharField(blank=True, help_text='Indicative budget text; not a quote.', max_length=255, verbose_name='estimated cost (note)')),
                ('line_status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.maintenanceplan')),
                ('recommended_product', models.ForeignKey(blank=True, help_text='SKU or bundle to propose (replacement, upgrade, service kit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mjop_line_recommendations', to='catalog.product', verbose_name='recommended product')),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mjop_lines', to='assets.asset', verbose_name='related asset')),
            ],
            options={
                'verbose_name': 'MJOP line',
                'verbose_name_plural': 'MJOP lines',
                'ordering': ['plan', 'plan_year', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecallCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('remedy_description', models.TextField(blank=True, verbose_name='remedy / action required')),
                ('announced_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Optional filter: typical product family affected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_campaigns', to='catalog.product')),
            ],
            options={
                'verbose_name': 'recall campaign',
                'verbose_name_plural': 'recall campaigns',
                'ordering': ['-announced_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetRecallLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending assessment'), ('action_required', 'Action required'), ('in_progress', 'Remedy in progress'), ('completed', 'Completed'), ('not_affected', 'Not affected'), ('exempt', 'Exempt / waived')], db_index=True, default='pending', max_length=24)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_links', to='assets.asset')),
                ('recall_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='assets.recallcampaign')),
            ],
            options={
                'verbose_name': 'asset recall link',
                'verbose_name_plural': 'asset recall links',
                'ordering': ['recall_campaign', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('recall_service', 'Recall / safety service'), ('calibration', 'Calibration'), ('warranty_claim', 'Warranty claim'), ('recommendation', 'Advisory / upsell note'), ('note', 'General note'), ('other', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('vendor_name', models.CharField(blank=True, max_length=200, verbose_name='vendor / technician')),
                ('reference_external', models.CharField(blank=True, help_text='RMA, work order, or ticket ID.', max_length=120, verbose_name='external reference')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_currency', models.CharField(blank=True, default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_created', to=settings.AUTH_USER_MODEL)),
                ('related_product', models.ForeignKey(blank=True, help_text='Spare part or replacement SKU, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to='catalog.product', verbose_name='related product')),
                ('recall_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to='assets.recallcampaign')),
            ],
            options={
                'verbose_name': 'asset event',
                'verbose_name_plural': 'asset events',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'is_archived'], name='assets_asse_organiz_784353_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetrecalllink',
            constraint=models.UniqueConstraint(fields=('recall_campaign', 'asset'), name='assets_assetrecalllink_unique_campaign_asset'),
        ),
    ]
