# Generated by Django 5.2.12 on 2026-04-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceplan',
            options={'ordering': ['-valid_from', '-created_at'], 'verbose_name': 'multi-year maintenance plan (MJOP)', 'verbose_name_plural': 'multi-year maintenance plans (MJOP)'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceplanline',
            options={'ordering': ['plan', 'plan_year', 'sort_order', 'id'], 'verbose_name': 'maintenance plan line', 'verbose_name_plural': 'maintenance plan lines'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='expected_end_of_life_date',
            field=models.DateField(blank=True, help_text='Planned replacement horizon for multi-year maintenance planning and sales advice.', null=True, verbose_name='expected end of life'),
        ),
        migrations.AlterField(
            model_name='maintenanceplanline',
            name='is_promoted',
            field=models.BooleanField(db_index=True, default=False, help_text='Highlight in customer-facing maintenance plan summaries and sales follow-up.', verbose_name='promote to customer'),
        ),
    ]
