# Generated by Django 5.2.12 on 2026-04-04 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_maintenance_plan_verbose_names'),
        ('relations', '0006_organization_unit_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOrganizationTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transferred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_transfers', to='assets.asset')),
                ('from_organization', models.ForeignKey(blank=True, help_text='Previous custodian; empty for initial registration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_from', to='relations.organization', verbose_name='from organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_to', to='relations.organization', verbose_name='to organization')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_organization_transfers_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset organization transfer',
                'verbose_name_plural': 'asset organization transfers',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
