# Generated by Django 5.2.12 on 2026-03-30 20:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'discount group',
                'verbose_name_plural': 'discount groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Short code for integrations (e.g. NL_HIGH).', max_length=32, verbose_name='tax code')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g. 21.00 for 21%.', max_digits=5, verbose_name='rate (%)')),
            ],
            options={
                'verbose_name': 'tax rate',
                'verbose_name_plural': 'tax rates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.productcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('short_description', models.CharField(blank=True, help_text='For quotes and order lines (max 255 characters).', max_length=255, verbose_name='short description')),
                ('long_description', models.TextField(blank=True, verbose_name='long description')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='brand / manufacturer')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('end_of_life', 'End of life'), ('unavailable', 'Unavailable')], db_index=True, default='draft', max_length=20, verbose_name='product status')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SKU')),
                ('ean_gtin', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='EAN / GTIN')),
                ('mpn', models.CharField(blank=True, max_length=120, verbose_name='MPN (manufacturer part number)')),
                ('upc_isbn', models.CharField(blank=True, max_length=32, verbose_name='UPC / ISBN')),
                ('length', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='length')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='width')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='height')),
                ('dimension_unit', models.CharField(blank=True, help_text='e.g. mm, cm', max_length=10, verbose_name='dimension unit')),
                ('weight_net', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='net weight')),
                ('weight_gross', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='gross weight')),
                ('weight_unit', models.CharField(blank=True, help_text='e.g. g, kg', max_length=10, verbose_name='weight unit')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='color')),
                ('material', models.CharField(blank=True, max_length=120, verbose_name='material')),
                ('size_or_volume', models.CharField(blank=True, help_text='e.g. clothing size or volume in liters.', max_length=120, verbose_name='size / volume')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price (cost)')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='standard list price')),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, help_text='Manufacturer suggested retail price.', max_digits=12, null=True, verbose_name='MSRP')),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 code (e.g. EUR).', max_length=3, verbose_name='currency')),
                ('unit_of_measure', models.CharField(blank=True, help_text='e.g. piece, box (12), pallet.', max_length=32, verbose_name='unit of measure')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, verbose_name='minimum order quantity (MOQ)')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='lead time (days)')),
                ('lead_time_text', models.CharField(blank=True, help_text='e.g. "2–3 business days" when not expressed as a single number of days.', max_length=120, verbose_name='lead time (text)')),
                ('warehouse_location', models.CharField(blank=True, max_length=120, verbose_name='warehouse location')),
                ('inventory_tracked', models.BooleanField(default=True, verbose_name='inventory tracked')),
                ('serial_number_required', models.BooleanField(default=False, verbose_name='serial number required')),
                ('warranty_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='warranty (months)')),
                ('maintenance_interval', models.CharField(blank=True, help_text='e.g. "Every 12 months".', max_length=120, verbose_name='maintenance interval')),
                ('depreciation_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='depreciation (months)')),
                ('asset_type', models.CharField(blank=True, choices=[('loan', 'Loan device'), ('sold', 'Sold device'), ('internal', 'Internal asset')], help_text='Used when this product becomes an installed asset.', max_length=20, null=True, verbose_name='asset type')),
                ('discount_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.discountgroup', verbose_name='discount group')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='category')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.taxrate', verbose_name='tax rate')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductConnectivitySpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('io_ports', models.TextField(blank=True, verbose_name='I/O ports')),
                ('wireless', models.TextField(blank=True, verbose_name='wireless connectivity')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_spec', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product connectivity specification',
                'verbose_name_plural': 'product connectivity specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductDisplaySpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagonal', models.CharField(blank=True, max_length=40, verbose_name='screen diagonal')),
                ('resolution', models.CharField(blank=True, max_length=80, verbose_name='resolution')),
                ('touchscreen_type', models.CharField(choices=[('none', 'None'), ('capacitive', 'Capacitive (PCAP)'), ('resistive', 'Resistive')], default='none', max_length=20, verbose_name='touchscreen type')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_spec', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product display specification',
                'verbose_name_plural': 'product display specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('datasheet', 'Datasheet / specifications'), ('manual', 'User manual'), ('certification', 'Certification'), ('msds', 'MSDS / safety sheet'), ('other', 'Other')], default='other', max_length=20, verbose_name='document type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='catalog/documents/%Y/%m/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product document',
                'verbose_name_plural': 'product documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='catalog/products/%Y/%m/', verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alternative text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['product', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductITSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operating_system', models.CharField(blank=True, max_length=200, verbose_name='operating system')),
                ('cpu', models.CharField(blank=True, max_length=200, verbose_name='processor (CPU)')),
                ('ram', models.CharField(blank=True, max_length=120, verbose_name='RAM')),
                ('storage', models.CharField(blank=True, max_length=120, verbose_name='storage')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_spec', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product IT specification',
                'verbose_name_plural': 'product IT specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.PositiveIntegerField(verbose_name='minimum quantity')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Leave empty for an open-ended tier (e.g. 50+).', null=True, verbose_name='maximum quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product price tier',
                'verbose_name_plural': 'product price tiers',
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrinterSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('print_technology', models.CharField(blank=True, max_length=120, verbose_name='print technology')),
                ('print_resolution', models.CharField(blank=True, max_length=80, verbose_name='print resolution')),
                ('print_width', models.CharField(blank=True, max_length=80, verbose_name='print width / media format')),
                ('cutter_type', models.CharField(blank=True, max_length=120, verbose_name='cutter / tear bar')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_spec', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product printer specification',
                'verbose_name_plural': 'product printer specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductScannerSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_engine', models.CharField(blank=True, max_length=200, verbose_name='scan engine')),
                ('drop_spec', models.CharField(blank=True, max_length=200, verbose_name='drop specification')),
                ('ip_rating', models.CharField(blank=True, max_length=40, verbose_name='IP rating')),
                ('battery_mah', models.PositiveIntegerField(blank=True, null=True, verbose_name='battery (mAh)')),
                ('battery_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='battery life (hours)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_spec', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product scanner specification',
                'verbose_name_plural': 'product scanner specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductBOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='quantity')),
                ('bundle_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='catalog.product', verbose_name='bundle product')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_of_bundles', to='catalog.product', verbose_name='component product')),
            ],
            options={
                'verbose_name': 'BOM line',
                'verbose_name_plural': 'BOM lines',
                'constraints': [models.UniqueConstraint(fields=('bundle_product', 'component_product'), name='catalog_bom_unique_bundle_component')],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('accessory', 'Accessory'), ('alternative', 'Alternative'), ('upsell', 'Upsell')], max_length=20, verbose_name='relation type')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='catalog.product', verbose_name='from product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='catalog.product', verbose_name='to product')),
            ],
            options={
                'verbose_name': 'product relation',
                'verbose_name_plural': 'product relations',
                'ordering': ['from_product', 'relation_type', 'sort_order', 'to_product'],
                'constraints': [models.UniqueConstraint(fields=('from_product', 'to_product', 'relation_type'), name='catalog_relation_unique_triple')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
    ]
