# Generated by Django 5.2.12 on 2026-03-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('view_product_purchase_price', 'Can view purchase price on the catalog frontend'), ('edit_product_pricing', 'Can edit list price, MSRP, currency, tax, and discount fields')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
