# Generated by Django 5.2.12 on 2026-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrelation',
            name='relation_type',
            field=models.CharField(choices=[('accessory', 'Accessory'), ('alternative', 'Alternative'), ('upsell', 'Upsell'), ('replacement', 'Replacement (EOL / discontinued)')], max_length=20, verbose_name='relation type'),
        ),
    ]
