# Generated by Django 5.2.12 on 2026-03-31 17:01

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productrelation_relation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('view_product_purchase_price', 'Can view purchase price on the catalog frontend'), ('edit_product_pricing', 'Can edit list price, MSRP, currency, tax, and discount fields'), ('archive_product', 'Can archive/unarchive products (soft delete)')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archived at'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived products are hidden from most users but retained for audit/history.', verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=catalog.models.product_image_upload_to, verbose_name='image'),
        ),
    ]
