# Generated by Django 5.2.12 on 2026-03-31 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-uploaded_at', 'pk'], 'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='file size (bytes)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='original filename'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='uploaded at'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.product', verbose_name='product'),
        ),
    ]
