# Generated by Django 5.2.12 on 2026-04-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_quote_relation_and_references'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Customer or third-party reference (e.g. their RFQ number).', max_length=80, verbose_name='external reference ID'),
        ),
        migrations.AddField(
            model_name='quote',
            name='internal_reference',
            field=models.CharField(blank=True, help_text='Your internal reference (e.g. CRM deal ID).', max_length=80, verbose_name='internal reference ID'),
        ),
        migrations.AddField(
            model_name='quote',
            name='relation_organization',
            field=models.ForeignKey(blank=True, help_text='Organization this quote is for (must be tagged as Customer or Prospect).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='relations.organization', verbose_name='customer / prospect'),
        ),
    ]
