# Generated by Django 5.2.12 on 2026-04-02 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productimage_options_productimage_file_size_and_more'),
        ('relations', '0005_organizationcategorytag_prospect'),
        ('sales', '0002_quote_relation_and_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, the quote is frozen (typically after an order was created from it).', verbose_name='locked'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='relation_organization',
            field=models.ForeignKey(blank=True, help_text='Copied from the quote when the order is created from a quote.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='relations.organization', verbose_name='customer / prospect'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.salesorder', verbose_name='sales order')),
                ('relation_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='relations.organization', verbose_name='bill-to organization')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['invoice', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_note', models.CharField(blank=True, help_text='e.g. bank reference, check number.', max_length=120, verbose_name='payment reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'invoice payment',
                'verbose_name_plural': 'invoice payments',
                'ordering': ['invoice', 'created_at'],
            },
        ),
    ]
