# Generated by Django 5.2.12 on 2026-04-02 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productimage_options_productimage_file_size_and_more'),
        ('sales', '0003_quote_lock_orders_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_orders_created', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_orders', to='sales.salesorder', verbose_name='sales order')),
            ],
            options={
                'verbose_name': 'fulfillment order',
                'verbose_name_plural': 'fulfillment orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('warehouse_location', models.CharField(blank=True, help_text='Bin/aisle snapshot from the product when this line was created.', max_length=120, verbose_name='warehouse location')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.fulfillmentorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_order_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['fulfillment_order', 'sort_order', 'id'],
            },
        ),
    ]
