# Generated by Django 5.2.12 on 2026-04-03 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_fulfillment_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('partially_shipped', 'Partially shipped'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], db_index=True, default='released', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders_created', to=settings.AUTH_USER_MODEL)),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='sales.fulfillmentorder', verbose_name='fulfillment order')),
                ('sales_order', models.ForeignKey(help_text='Denormalized from the fulfillment order for reporting and navigation.', on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='sales.salesorder', verbose_name='sales order')),
            ],
            options={
                'verbose_name': 'shipping order',
                'verbose_name_plural': 'shipping orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Display order within the shipping order (1 = first shipment).')),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.shippingorder')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['shipping_order', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fulfillment_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_lines', to='sales.fulfillmentorderline', verbose_name='fulfillment line')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.shippingorder')),
            ],
            options={
                'ordering': ['shipping_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.shipment')),
                ('shipping_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='sales.shippingorderline', verbose_name='shipping order line')),
            ],
            options={
                'ordering': ['shipment', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shippingorderline',
            constraint=models.UniqueConstraint(fields=('shipping_order', 'fulfillment_line'), name='sales_shippingorderline_unique_fulfillment_line_per_order'),
        ),
        migrations.AddConstraint(
            model_name='shipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'shipping_order_line'), name='sales_shipmentline_unique_line_per_shipment'),
        ),
    ]
